swagger: "2.0"
info:
  version: "0.0.1"
  title: Relay API
# during dev, should point to your local machine
host: 10.246.11.131:10010
# basePath prefixes all resource paths 
basePath: /
# tags
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /action:
    # binds a127 app logic to a route
    x-swagger-router-controller: relay
    get:
      description: Commits action to Edison board
      # used as the method name of the controller
      operationId: relay
      parameters:
        - name: deviceId
          in: query
          description: The device Id of relay 
          required: true
          type: string
        - name: action
          in: query
          description: The action to be performed. On/Off
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/RelayAction"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  RelayAction:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
